# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-23 07:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0001_initial'),
        ('account', '0002_receives'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='receivedMessages',
            field=models.ManyToManyField(related_name='received_by', through='account.Receives', to='mail.Message'),
        ),
    ]
